export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const FACEBOOK = 'FACEBOOK_ACCESS_CODE';
export const GOOGLE = 'GOOGLE_ACCESS_CODE';
export const TWITTER = 'TWITTER_ACCESS_CODE';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const FETCHING = 'FETCHING';
export const FETCH_FAILED = 'FETCH_FAILED';

export const GET_ARTICLES = 'GET_ARTICLES';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const ISFETCHING = 'ISFETCHING';
export const ARTICLE_IS_SUCCESS = 'ARTICLE_IS_SUCCESS';
export const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE';

export const GET_PROFILE = 'GET_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_ERROR = 'ADD_ERROR';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const LIKE_ARTICLE_REQUEST = 'LIKE_ARTICLE_REQUEST';
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';
export const DISLIKE_ARTICLE_REQUEST = 'DISLIKE_ARTICLE_REQUEST';
export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS';
export const DISLIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';

export const BOOKMARK_ARTICLE = 'BOOKMARK_ARTICLE';
export const UNBOOKMARK_ARTICLE = 'UNBOOKMARK_ARTICLE';
export const BOOKMARK_ARTICLE_FAILURE = 'BOOKMARK_ARTICLE_FAILURE';
export const GET_ALL_BOOKMARKS_SUCCESS = 'GET_ALL_BOOKMARKS_SUCCESS';
export const GET_ALL_BOOKMARKS_FAIL = 'GET_ALL_BOOKMARKS_FAIL';

export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const SUCCESSFUL_RATING = 'SUCCESS_RATING';
export const RATING_ERROR = 'RATING_ERROR';
export const RATING_REQUEST = 'RATING_REQUEST';

export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const EDITED = 'EDITED';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const POST_ARTICLE_ERROR = 'POST_ARTICLE_ERROR';
export const GET_SINGLE_ARTICLE_ERROR = 'GET_SINGLE_ARTICLE_ERROR';
